/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

;
import javax.swing.table.DefaultTableModel;
import swing.ScrollBar;
import Model.Model_Card;
import Model.ResultSetTableModel;
import Model.StatusType;
import Model.TableGradientCell;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.Color;
import java.awt.Font;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import mini_projet_errahem_karim.connexion;

/**
 *
 * @author Karim
 */
public class Form_Home extends javax.swing.JPanel {
 

    /**
     * Creates new form Form_Home
     */
    public int getNumberOfdietplans() {
     connexion c = new connexion();
        int numberOfdiets = 0;
     try {
            String query = "SELECT COUNT(*) AS totaldiets FROM dietplans";
              try (PreparedStatement pstmt = c.con.prepareStatement(query)) {
                  ResultSet resultSet = pstmt.executeQuery();
                  if (resultSet.next()) {
                      numberOfdiets = resultSet.getInt("totaldiets");
                  }
                  resultSet.close();
              }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return numberOfdiets;
    
    
    }
    public int getNumberOfStaff(){
    connexion c = new connexion();
        int numberOfuser = 0;
        try {
            String query = "SELECT COUNT(*) AS total_user FROM users";
              try (PreparedStatement pstmt = c.con.prepareStatement(query)) {
                  ResultSet resultSet = pstmt.executeQuery();
                  if (resultSet.next()) {
                      numberOfuser = resultSet.getInt("total_user");
                  }
                  resultSet.close();
              }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return numberOfuser;
    }
     public int getNumberOfCustomers() {
          connexion c = new connexion();
        int numberOfCustomers = 0;
        try {
            String query = "SELECT COUNT(*) AS total_customers FROM CustomerProfiles";
              try (PreparedStatement pstmt = c.con.prepareStatement(query)) {
                  ResultSet resultSet = pstmt.executeQuery();
                  if (resultSet.next()) {
                      numberOfCustomers = resultSet.getInt("total_customers");
                  }
                  resultSet.close();
              }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return numberOfCustomers;
    }
    public Form_Home() {
       
        initComponents();
         int totalCustomers = getNumberOfCustomers();
         int numberOfdiets=getNumberOfdietplans();
         int staff = getNumberOfStaff();
         loadCustomers();
        
        card1.setData(new Model_Card(new ImageIcon(getClass().getResource("/icon/health_checkup_30px.png")), "clients", String.valueOf(totalCustomers), ""));
        card2.setData(new Model_Card(new ImageIcon(getClass().getResource("/icon/bitten_apple_30px.png")), "plans de régime", String.valueOf(numberOfdiets), ""));
        card3.setData(new Model_Card(new ImageIcon(getClass().getResource("/icon/staff_30px.png")), "staff ", String.valueOf(staff), ""));
             //  add row table
  Tclient.setDefaultRenderer(Object.class, new TableGradientCell());
        
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        card1 = new component.Card();
        card2 = new component.Card();
        card3 = new component.Card();
        jPanel1 = new swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        Tclient = new javax.swing.JTable();

        setBackground(new java.awt.Color(242, 242, 242));

        panel.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        card1.setColor1(new java.awt.Color(142, 142, 250));
        card1.setColor2(new java.awt.Color(123, 123, 245));
        panel.add(card1);

        card2.setColor1(new java.awt.Color(186, 123, 247));
        card2.setColor2(new java.awt.Color(167, 94, 62));
        panel.add(card2);

        card3.setColor1(new java.awt.Color(241, 208, 62));
        card3.setColor2(new java.awt.Color(211, 184, 61));
        panel.add(card3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Table des clients");

        Tclient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tclient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        Tclient.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        Tclient.setFocusable(false);
        Tclient.setGridColor(new java.awt.Color(255, 255, 255));
        Tclient.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Tclient.setRowHeight(25);
        Tclient.setShowHorizontalLines(false);
        Tclient.setShowVerticalLines(false);
        Tclient.getTableHeader().setReorderingAllowed(false);
        Tclient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TclientMouseClicked(evt);
            }
        });
        scroll.setViewportView(Tclient);
        if (Tclient.getColumnModel().getColumnCount() > 0) {
            Tclient.getColumnModel().getColumn(0).setPreferredWidth(10);
            Tclient.getColumnModel().getColumn(1).setPreferredWidth(10);
            Tclient.getColumnModel().getColumn(2).setPreferredWidth(10);
            Tclient.getColumnModel().getColumn(3).setPreferredWidth(10);
            Tclient.getColumnModel().getColumn(4).setPreferredWidth(80);
            Tclient.getColumnModel().getColumn(5).setPreferredWidth(80);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(578, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TclientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TclientMouseClicked
      boolean a = Tclient.isEditing();
      if (a==false){
      JOptionPane.showMessageDialog(null, "Tu ne peut pas modifier");
      
      }
    }//GEN-LAST:event_TclientMouseClicked
 
 
    


public void loadCustomers() {
  
    String[] enrg ={"Nom", "Taille", "Poits", "Age", "Sexe", "Date","But"};
    DefaultTableModel m1 = new DefaultTableModel(null,enrg);
 String [] affichage = new String [7];
    connexion c = new connexion();
    try {
        String query1 = "SELECT customer_name AS Nom, profile_id AS id_profil FROM customerprofilemapping"; 

        PreparedStatement pstmt = c.con.prepareStatement(query1);
        ResultSet resultSet = pstmt.executeQuery();
        while (resultSet.next()) {
            String nom = resultSet.getString("Nom");
            int idpro = resultSet.getInt("id_profil");
            String query2 = "SELECT height AS taille, weight AS poits, age AS agepro, gender AS sexepro, goal AS butpro, created_at AS date, goal AS but FROM customerprofiles WHERE id=?";
            PreparedStatement pstmt1 = c.con.prepareStatement(query2);
            pstmt1.setInt(1, idpro);
            ResultSet res = pstmt1.executeQuery(); 

            if (res.next()) {
           double taille = res.getDouble("taille");
                double poits = res.getDouble("poits");
                int age = res.getInt("agepro");
                String sexe = res.getString("sexepro");
                String date = res.getString("date");
                String but = res.getString("but");
                affichage[0]=nom;
                affichage[1]=String.valueOf(taille);
                 affichage[2]=String.valueOf(poits);
                  affichage[3]=String.valueOf(age);
                   affichage[4]=String.valueOf(sexe);
                    affichage[5]=String.valueOf(date);
                     affichage[6]=String.valueOf(but);
                m1.addRow(affichage);
                
            }
            res.close(); 
            pstmt1.close();
        }
        resultSet.close(); 
        pstmt.close(); 

    
  Tclient.setModel(m1);
    } catch (SQLException e) {
        e.printStackTrace();
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tclient;
    private component.Card card1;
    private component.Card card2;
    private component.Card card3;
    private javax.swing.JLabel jLabel1;
    private swing.PanelBorder jPanel1;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scroll;
    // End of variables declaration//GEN-END:variables
}
