/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import mini_projet_errahem_karim.connexion;

/**
 *
 * @author Karim
 */
public class Form2 extends javax.swing.JPanel {

    /**
     * Creates new form Form2
     */
    int totalCalories =  0 ;
        int totalFats =  0 ;
        int totalProteins =  0 ;
   
     
        
        // Fermeture des ressources JDBC
  
void combo (){


dinner1.loadMealNames("dinner");
dinner1.populateComboBox();
dinner2.loadMealNames("dinner");
dinner2.populateComboBox();
dinner3.loadMealNames("dinner");
dinner3.populateComboBox();
dinner4.loadMealNames("dinner");
dinner4.populateComboBox();
dinner5.loadMealNames("dinner");
dinner5.populateComboBox();
dinner6.loadMealNames("dinner");
dinner6.populateComboBox();
dinner7.loadMealNames("dinner");
dinner7.populateComboBox();

breakfast1.loadMealNames();
breakfast1.populateComboBox();
breakfast2.loadMealNames();
breakfast2.populateComboBox();
breakfast3.loadMealNames();
breakfast3.populateComboBox();
breakfast4.loadMealNames();
breakfast4.populateComboBox();
breakfast5.loadMealNames();
breakfast5.populateComboBox();
breakfast6.loadMealNames();
breakfast6.populateComboBox();
breakfast7.loadMealNames();
breakfast7.populateComboBox();

lunch1.loadMealNames("lunch");
lunch1.populateComboBox();
lunch2.loadMealNames("lunch");
lunch2.populateComboBox();
lunch3.loadMealNames("lunch");
lunch3.populateComboBox();
lunch4.loadMealNames("lunch");
lunch4.populateComboBox();
lunch5.loadMealNames("lunch");
lunch5.populateComboBox();
lunch6.loadMealNames("lunch");
lunch6.populateComboBox();
lunch7.loadMealNames("lunch");
lunch7.populateComboBox();
}

 
    int uid;
    public Form2(int id) {
        this.uid=id;
      
        initComponents();
        combo ();
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entete1 = new component.Entete();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        breakfast1 = new swing.breakfast();
        breakfast2 = new swing.breakfast();
        breakfast3 = new swing.breakfast();
        breakfast4 = new swing.breakfast();
        breakfast5 = new swing.breakfast();
        breakfast6 = new swing.breakfast();
        breakfast7 = new swing.breakfast();
        lunch1 = new swing.lunch();
        lunch2 = new swing.lunch();
        lunch3 = new swing.lunch();
        lunch4 = new swing.lunch();
        lunch5 = new swing.lunch();
        lunch6 = new swing.lunch();
        lunch7 = new swing.lunch();
        dinner1 = new swing.lunch();
        dinner2 = new swing.lunch();
        dinner3 = new swing.lunch();
        dinner4 = new swing.lunch();
        dinner5 = new swing.lunch();
        dinner6 = new swing.lunch();
        dinner7 = new swing.lunch();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nomderegime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Description_de_regime = new javax.swing.JTextField();
        nbcal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        nbproteins = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nbfats = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ajouterunregime = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 242, 242));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ajouter un regime");

        javax.swing.GroupLayout entete1Layout = new javax.swing.GroupLayout(entete1);
        entete1.setLayout(entete1Layout);
        entete1Layout.setHorizontalGroup(
            entete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entete1Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        entete1Layout.setVerticalGroup(
            entete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, entete1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(40, 40, 40))
        );

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Jour 1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Jour 2");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Jour 3");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jour 4");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Jour 5");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Jour 6");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Jour 7");

        breakfast1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                breakfast1ItemStateChanged(evt);
            }
        });

        breakfast2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                breakfast2ItemStateChanged(evt);
            }
        });

        breakfast3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                breakfast3ItemStateChanged(evt);
            }
        });

        breakfast4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                breakfast4ItemStateChanged(evt);
            }
        });

        breakfast5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                breakfast5ItemStateChanged(evt);
            }
        });

        breakfast6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                breakfast6ItemStateChanged(evt);
            }
        });

        breakfast7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                breakfast7ItemStateChanged(evt);
            }
        });

        lunch1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lunch1ItemStateChanged(evt);
            }
        });

        lunch2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lunch2ItemStateChanged(evt);
            }
        });

        lunch3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lunch3ItemStateChanged(evt);
            }
        });

        lunch4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lunch4ItemStateChanged(evt);
            }
        });

        lunch5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lunch5ItemStateChanged(evt);
            }
        });

        lunch6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lunch6ItemStateChanged(evt);
            }
        });

        dinner1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dinner1ItemStateChanged(evt);
            }
        });

        dinner2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dinner2ItemStateChanged(evt);
            }
        });

        dinner3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dinner3ItemStateChanged(evt);
            }
        });

        dinner4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dinner4ItemStateChanged(evt);
            }
        });

        dinner5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dinner5ItemStateChanged(evt);
            }
        });

        dinner6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dinner6ItemStateChanged(evt);
            }
        });

        dinner7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dinner7ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(breakfast1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(breakfast2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(breakfast3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(breakfast4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(breakfast5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(breakfast6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(breakfast7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dinner5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dinner6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dinner7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lunch6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunch5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunch4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunch2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunch1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunch7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunch3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breakfast1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(breakfast2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lunch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(breakfast3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(breakfast4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lunch4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(breakfast5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunch5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(breakfast6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunch6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(breakfast7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunch7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nom de regime");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Description de regime");

        nbcal.setBorder(null);

        jLabel11.setText("Nombre de calorie");

        nbproteins.setBorder(null);

        jLabel13.setText("nombre de proteins");

        nbfats.setBorder(null);

        jLabel12.setText("Nombre de fats");

        ajouterunregime.setText("Ajouter");
        ajouterunregime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterunregimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entete1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(ajouterunregime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nbfats, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nbcal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Nomderegime, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(176, 176, 176)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(Description_de_regime, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(28, 28, 28)
                                .addComponent(nbproteins, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(entete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(Description_de_regime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nomderegime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbcal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(nbproteins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(nbfats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(ajouterunregime)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
private List<Integer> getSelectedMealIds(JComboBox[] mealComboBoxes) {
    List<Integer> selectedMealIds = new ArrayList<>();
    for (JComboBox comboBox : mealComboBoxes) {
        String selectedMeal = comboBox.getSelectedItem().toString();
        int mealId = getMealIdByName(selectedMeal);
        if (mealId != -1) {
            selectedMealIds.add(mealId);
        }
    }
    return selectedMealIds;
}
             
               
                

    private void ajouterunregimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterunregimeActionPerformed
     String nomRegime = Nomderegime.getText().trim();
    String descriptionRegime = Description_de_regime.getText().trim();
     List<Integer> selectedMealIds = new ArrayList<>();
    JComboBox[] mealComboBoxes = {breakfast1,dinner1,lunch1, breakfast2,dinner2,lunch2,breakfast3,dinner3,lunch3,breakfast4,dinner4,lunch4 ,breakfast5,dinner5,lunch5, breakfast6,dinner6,lunch6,breakfast7,dinner7,lunch7};
     selectedMealIds = getSelectedMealIds(mealComboBoxes);
    if (nomRegime.isEmpty() || descriptionRegime.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs.", "Erreur", JOptionPane.ERROR_MESSAGE);
        return;}
connexion c = new connexion();
String insertDietPlanQuery = "INSERT INTO dietplans (name, description, User_id, nbcal, proteins, fats) VALUES (?, ?, ?, ?, ?, ?)";
try {PreparedStatement insertDietPlanStmt = c.con.prepareStatement(insertDietPlanQuery, Statement.RETURN_GENERATED_KEYS);
 insertDietPlanStmt.setString(1, nomRegime);
 insertDietPlanStmt.setString(2, descriptionRegime);
 insertDietPlanStmt.setString(3, String.valueOf(uid));
        insertDietPlanStmt.setString(4, nbcal.getText());
        insertDietPlanStmt.setString(5, nbproteins.getText());
        insertDietPlanStmt.setString(6, nbfats.getText());
        insertDietPlanStmt.executeUpdate();
ResultSet generatedKeys = insertDietPlanStmt.getGeneratedKeys();
        int dietplanId = -1;
        if (generatedKeys.next()) {
            dietplanId = generatedKeys.getInt(1);}
if (dietplanId != -1) {
    int mealIndex = 0; // Indice pour parcourir les repas sélectionnés
    for (int i = 0; i < 7; i++) { // Boucle pour chaque jour de la semaine
        for (int k = 0; k < 3; k++) { // Boucle pour chaque repas à ajouter ce jour-là
            if (mealIndex < selectedMealIds.size()) { // Vérifie si nous avons encore des repas à ajouter
                String insertDietPlanMealQuery = "INSERT INTO dietplanmeals (dietplan_id, breakfast, dinner, lunch, day) VALUES (?, ?, ?, ?, ?)";
                PreparedStatement insertMealStmt = c.con.prepareStatement(insertDietPlanMealQuery);
                insertMealStmt.setInt(1, dietplanId);
                insertMealStmt.setInt(2, selectedMealIds.get(mealIndex));
                insertMealStmt.setInt(3, selectedMealIds.get(mealIndex + 1));
                insertMealStmt.setInt(4, selectedMealIds.get(mealIndex + 2));
                insertMealStmt.setString(5, String.valueOf(i+1)); // Day of the week
                insertMealStmt.executeUpdate();
                mealIndex += 3; // Passer au prochain ensemble de repas
            }
        }
    }
}

Nomderegime.setText("");
Description_de_regime.setText("");
JOptionPane.showMessageDialog(this, "Le régime a été ajouté avec succès !", "Succès", JOptionPane.INFORMATION_MESSAGE);
} catch (SQLException e) {
e.printStackTrace();
JOptionPane.showMessageDialog(this, "Une erreur est survenue lors de l'ajout du régime.", "Erreur", JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_ajouterunregimeActionPerformed

    private void breakfast1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_breakfast1ItemStateChanged
      totalCalories= totalCalories - breakfast1.nbcal;
      totalFats = totalFats -  breakfast1.nbfat;
      totalProteins = totalProteins - breakfast1.nbpro;
      breakfast1.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + breakfast1.nbcal;
      totalFats = totalFats +  breakfast1.nbfat;
      totalProteins = totalProteins + breakfast1.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_breakfast1ItemStateChanged

    private void breakfast2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_breakfast2ItemStateChanged
      totalCalories= totalCalories - breakfast2.nbcal;
      totalFats = totalFats -  breakfast2.nbfat;
      totalProteins = totalProteins - breakfast2.nbpro;
      breakfast2.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + breakfast2.nbcal;
      totalFats = totalFats +  breakfast2.nbfat;
      totalProteins = totalProteins + breakfast2.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_breakfast2ItemStateChanged

    private void breakfast3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_breakfast3ItemStateChanged
       totalCalories= totalCalories - breakfast3.nbcal;
      totalFats = totalFats -  breakfast3.nbfat;
      totalProteins = totalProteins - breakfast3.nbpro;
      breakfast3.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + breakfast3.nbcal;
      totalFats = totalFats +  breakfast3.nbfat;
      totalProteins = totalProteins + breakfast3.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_breakfast3ItemStateChanged

    private void breakfast4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_breakfast4ItemStateChanged
       totalCalories= totalCalories - breakfast4.nbcal;
      totalFats = totalFats -  breakfast4.nbfat;
      totalProteins = totalProteins - breakfast4.nbpro;
      breakfast4.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + breakfast4.nbcal;
      totalFats = totalFats +  breakfast4.nbfat;
      totalProteins = totalProteins + breakfast4.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_breakfast4ItemStateChanged

    private void breakfast5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_breakfast5ItemStateChanged
       totalCalories= totalCalories - breakfast5.nbcal;
      totalFats = totalFats -  breakfast5.nbfat;
      totalProteins = totalProteins - breakfast5.nbpro;
      breakfast5.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + breakfast5.nbcal;
      totalFats = totalFats +  breakfast5.nbfat;
      totalProteins = totalProteins + breakfast5.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_breakfast5ItemStateChanged

    private void breakfast6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_breakfast6ItemStateChanged
         totalCalories= totalCalories - breakfast6.nbcal;
      totalFats = totalFats -  breakfast6.nbfat;
      totalProteins = totalProteins - breakfast6.nbpro;
      breakfast6.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + breakfast6.nbcal;
      totalFats = totalFats +  breakfast6.nbfat;
      totalProteins = totalProteins + breakfast6.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_breakfast6ItemStateChanged

    private void breakfast7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_breakfast7ItemStateChanged
        totalCalories= totalCalories - breakfast7.nbcal;
      totalFats = totalFats -  breakfast7.nbfat;
      totalProteins = totalProteins - breakfast7.nbpro;
      breakfast7.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + breakfast7.nbcal;
      totalFats = totalFats +  breakfast7.nbfat;
      totalProteins = totalProteins + breakfast7.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_breakfast7ItemStateChanged

    private void dinner1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dinner1ItemStateChanged
     totalCalories= totalCalories - dinner1.nbcal;
      totalFats = totalFats -  dinner1.nbfat;
      totalProteins = totalProteins - dinner1.nbpro;
      dinner1.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + dinner1.nbcal;
      totalFats = totalFats +  dinner1.nbfat;
      totalProteins = totalProteins + dinner1.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_dinner1ItemStateChanged

    private void dinner2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dinner2ItemStateChanged
       totalCalories= totalCalories - dinner2.nbcal;
      totalFats = totalFats -  dinner2.nbfat;
      totalProteins = totalProteins - dinner2.nbpro;
      dinner2.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + dinner2.nbcal;
      totalFats = totalFats +  dinner2.nbfat;
      totalProteins = totalProteins + dinner2.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_dinner2ItemStateChanged

    private void dinner3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dinner3ItemStateChanged
      totalCalories= totalCalories - dinner3.nbcal;
      totalFats = totalFats -  dinner3.nbfat;
      totalProteins = totalProteins - dinner3.nbpro;
      dinner3.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + dinner3.nbcal;
      totalFats = totalFats +  dinner3.nbfat;
      totalProteins = totalProteins + dinner3.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_dinner3ItemStateChanged

    private void dinner4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dinner4ItemStateChanged
     totalCalories= totalCalories - dinner4.nbcal;
      totalFats = totalFats -  dinner4.nbfat;
      totalProteins = totalProteins - dinner4.nbpro;
      dinner4.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + dinner4.nbcal;
      totalFats = totalFats +  dinner4.nbfat;
      totalProteins = totalProteins + dinner4.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_dinner4ItemStateChanged

    private void dinner5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dinner5ItemStateChanged
    totalCalories= totalCalories - dinner5.nbcal;
      totalFats = totalFats -  dinner5.nbfat;
      totalProteins = totalProteins - dinner5.nbpro;
      dinner5.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + dinner5.nbcal;
      totalFats = totalFats +  dinner5.nbfat;
      totalProteins = totalProteins + dinner5.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_dinner5ItemStateChanged

    private void dinner6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dinner6ItemStateChanged
     totalCalories= totalCalories - dinner6.nbcal;
      totalFats = totalFats -  dinner6.nbfat;
      totalProteins = totalProteins - dinner6.nbpro;
      dinner6.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + dinner6.nbcal;
      totalFats = totalFats +  dinner6.nbfat;
      totalProteins = totalProteins + dinner6.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_dinner6ItemStateChanged

    private void dinner7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dinner7ItemStateChanged
       totalCalories= totalCalories - dinner7.nbcal;
      totalFats = totalFats -  dinner7.nbfat;
      totalProteins = totalProteins - dinner7.nbpro;
      dinner7.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + dinner7.nbcal;
      totalFats = totalFats +  dinner7.nbfat;
      totalProteins = totalProteins + dinner7.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_dinner7ItemStateChanged

    private void lunch1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lunch1ItemStateChanged
          totalCalories= totalCalories - lunch1.nbcal;
      totalFats = totalFats -  lunch1.nbfat;
      totalProteins = totalProteins - lunch1.nbpro;
      lunch1.calculerInformationsNutritionnellesRepas();
       totalCalories= totalCalories + lunch1.nbcal;
      totalFats = totalFats +  lunch1.nbfat;
      totalProteins = totalProteins + lunch1.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_lunch1ItemStateChanged

    private void lunch2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lunch2ItemStateChanged
        totalCalories= totalCalories - lunch2.nbcal;
              totalFats = totalFats -  lunch2.nbfat;
       totalProteins = totalProteins - lunch2.nbpro;
      lunch2.calculerInformationsNutritionnellesRepas();
        totalCalories= totalCalories + lunch2.nbcal;
              totalFats = totalFats +  lunch2.nbfat;
       totalProteins = totalProteins + lunch2.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_lunch2ItemStateChanged

    private void lunch3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lunch3ItemStateChanged
        totalCalories= totalCalories - lunch3.nbcal;
              totalFats = totalFats -  lunch3.nbfat;
       totalProteins = totalProteins - lunch3.nbpro;
      lunch3.calculerInformationsNutritionnellesRepas();
        totalCalories= totalCalories + lunch3.nbcal;
              totalFats = totalFats +  lunch3.nbfat;
       totalProteins = totalProteins + lunch3.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_lunch3ItemStateChanged

    private void lunch4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lunch4ItemStateChanged
        totalCalories= totalCalories - lunch4.nbcal;
              totalFats = totalFats -  lunch4.nbfat;
       totalProteins = totalProteins - lunch4.nbpro;
      lunch4.calculerInformationsNutritionnellesRepas();
        totalCalories= totalCalories + lunch4.nbcal;
              totalFats = totalFats +  lunch4.nbfat;
       totalProteins = totalProteins + lunch4.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_lunch4ItemStateChanged

    private void lunch5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lunch5ItemStateChanged
       totalCalories= totalCalories - lunch5.nbcal;
              totalFats = totalFats -  lunch5.nbfat;
       totalProteins = totalProteins - lunch5.nbpro;
      lunch5.calculerInformationsNutritionnellesRepas();
        totalCalories= totalCalories + lunch5.nbcal;
              totalFats = totalFats +  lunch5.nbfat;
       totalProteins = totalProteins + lunch5.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_lunch5ItemStateChanged

    private void lunch6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lunch6ItemStateChanged
        totalCalories= totalCalories - lunch6.nbcal;
              totalFats = totalFats -  lunch6.nbfat;
       totalProteins = totalProteins - lunch6.nbpro;
      lunch6.calculerInformationsNutritionnellesRepas();
        totalCalories= totalCalories + lunch6.nbcal;
              totalFats = totalFats +  lunch6.nbfat;
       totalProteins = totalProteins + lunch6.nbpro;
      InformationsNutritionnellesRepas();
    }//GEN-LAST:event_lunch6ItemStateChanged
private int[] getNutritionalInfoByMealName(String mealName) {
    connexion c = new connexion();
    String query = "SELECT SUM(fi.calories * mi.quantity) AS totalCalories, " +
                   "SUM(fi.fats * mi.quantity) AS totalFats, " +
                   "SUM(fi.proteins * mi.quantity) AS totalProteins " +
                   "FROM meals m " +
                   "INNER JOIN mealitems mi ON m.id = mi.meal_id " +
                   "INNER JOIN fooditems fi ON mi.food_item_id = fi.id " +
                   "WHERE m.name = ?";
    try {
        PreparedStatement pstmt = c.con.prepareStatement(query);
        pstmt.setString(1, mealName);
        ResultSet rs = pstmt.executeQuery();
        if (rs.next()) {
            int totalCalories = rs.getInt("totalCalories");
            int totalFats = rs.getInt("totalFats");
            int totalProteins = rs.getInt("totalProteins");
            return new int[]{totalCalories, totalFats, totalProteins};
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return new int[]{0, 0, 0};  // Return [0, 0, 0] if nutritional info not found
}

private void InformationsNutritionnellesRepas() {
   
   
        nbcal.setText(String.valueOf(totalCalories));
        nbfats.setText(String.valueOf(totalFats));
        nbproteins.setText(String.valueOf(totalProteins));

        // Désactiver les champs après le calcul
        nbcal.setEnabled(false);
        nbfats.setEnabled(false);
        nbproteins.setEnabled(false);
    
}
private void addMealToDietPlan(PreparedStatement insertMealStmt, int dietplanId, int idmealName,  int dayOfWeek) throws SQLException {
    
   
       
        insertMealStmt.setInt(1, dietplanId);
        insertMealStmt.setInt(2, idmealName);
        insertMealStmt.setString(3, String.valueOf(dayOfWeek)); // Day of the week
     
        insertMealStmt.executeUpdate();
    
}

private int getMealIdByName(String mealName) {
    connexion c = new connexion();
    String query = "SELECT id FROM meals WHERE name = ?";
    try {
        PreparedStatement pstmt = c.con.prepareStatement(query);
        pstmt.setString(1, mealName);
        ResultSet rs = pstmt.executeQuery();
        if (rs.next()) {
            return rs.getInt("id");
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return -1; // Retourne -1 si le repas n'est pas trouvé
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Description_de_regime;
    private javax.swing.JTextField Nomderegime;
    private javax.swing.JButton ajouterunregime;
    private swing.breakfast breakfast1;
    private swing.breakfast breakfast2;
    private swing.breakfast breakfast3;
    private swing.breakfast breakfast4;
    private swing.breakfast breakfast5;
    private swing.breakfast breakfast6;
    private swing.breakfast breakfast7;
    private swing.lunch dinner1;
    private swing.lunch dinner2;
    private swing.lunch dinner3;
    private swing.lunch dinner4;
    private swing.lunch dinner5;
    private swing.lunch dinner6;
    private swing.lunch dinner7;
    private component.Entete entete1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private swing.lunch lunch1;
    private swing.lunch lunch2;
    private swing.lunch lunch3;
    private swing.lunch lunch4;
    private swing.lunch lunch5;
    private swing.lunch lunch6;
    private swing.lunch lunch7;
    private javax.swing.JTextField nbcal;
    private javax.swing.JTextField nbfats;
    private javax.swing.JTextField nbproteins;
    // End of variables declaration//GEN-END:variables
}
