/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import component.Output;
import component.out;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import mini_projet_errahem_karim.connexion;

/**
 *
 * @author Karim
 */
public class Form1 extends javax.swing.JPanel {

    /**
     * Creates new form Form1
     */
    public Form1() {
        initComponents();
       maladiepanel1.setVisible(false);
      allergiepanel.setVisible(false);
      entete_tab();
      remplir_tab();
      populateComboBox();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroupmaladie = new javax.swing.ButtonGroup();
        buttonGroupallergie = new javax.swing.ButtonGroup();
        entete1 = new component.Entete();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablenewpatients = new javax.swing.JTable();
        label = new javax.swing.JLabel();
        Maladieoui = new javax.swing.JRadioButton();
        Maladienon = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        alergieoui = new javax.swing.JRadioButton();
        allergienon = new javax.swing.JRadioButton();
        allergiepanel = new javax.swing.JPanel();
        Description = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        desaller = new javax.swing.JTextArea();
        maladiepanel1 = new javax.swing.JPanel();
        Description1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        desmalad = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        regimes = new javax.swing.JComboBox();
        poids = new javax.swing.JLabel();
        Nouvpoids = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Nouvtaille = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        But = new javax.swing.JTextField();

        setBackground(new java.awt.Color(242, 242, 242));
        setPreferredSize(new java.awt.Dimension(837, 511));

        javax.swing.GroupLayout entete1Layout = new javax.swing.GroupLayout(entete1);
        entete1.setLayout(entete1Layout);
        entete1Layout.setHorizontalGroup(
            entete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        entete1Layout.setVerticalGroup(
            entete1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jTablenewpatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablenewpatients);

        label.setText("Regimes");

        buttonGroupmaladie.add(Maladieoui);
        Maladieoui.setText("Oui");
        Maladieoui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaladieouiMouseClicked(evt);
            }
        });

        buttonGroupmaladie.add(Maladienon);
        Maladienon.setText("Non");
        Maladienon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaladienonMouseClicked(evt);
            }
        });

        jLabel2.setText("Maladies");

        jLabel3.setText("Allergies");

        buttonGroupallergie.add(alergieoui);
        alergieoui.setText("Oui");
        alergieoui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alergieouiMouseClicked(evt);
            }
        });

        buttonGroupallergie.add(allergienon);
        allergienon.setText("Non");
        allergienon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allergienonMouseClicked(evt);
            }
        });

        Description.setText("Description");

        desaller.setColumns(20);
        desaller.setRows(5);
        jScrollPane2.setViewportView(desaller);

        javax.swing.GroupLayout allergiepanelLayout = new javax.swing.GroupLayout(allergiepanel);
        allergiepanel.setLayout(allergiepanelLayout);
        allergiepanelLayout.setHorizontalGroup(
            allergiepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allergiepanelLayout.createSequentialGroup()
                .addGroup(allergiepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allergiepanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Description))
                    .addGroup(allergiepanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        allergiepanelLayout.setVerticalGroup(
            allergiepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allergiepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Description)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Description1.setText("Description");

        desmalad.setColumns(20);
        desmalad.setRows(5);
        jScrollPane3.setViewportView(desmalad);

        javax.swing.GroupLayout maladiepanel1Layout = new javax.swing.GroupLayout(maladiepanel1);
        maladiepanel1.setLayout(maladiepanel1Layout);
        maladiepanel1Layout.setHorizontalGroup(
            maladiepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maladiepanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(maladiepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Description1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        maladiepanel1Layout.setVerticalGroup(
            maladiepanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maladiepanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Description1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("Donner un regime");

        poids.setText("Poids (kg)");

        jLabel5.setText("Taille (cm)");

        jLabel6.setText("But (kg)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(maladiepanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(allergiepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Maladieoui, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Maladienon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(poids)
                            .addComponent(jLabel5))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nouvtaille, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(Nouvpoids))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(But, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(regimes, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(alergieoui)
                        .addGap(118, 118, 118)
                        .addComponent(allergienon)
                        .addGap(113, 113, 113))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poids)
                            .addComponent(Nouvpoids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(But, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Nouvtaille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label)
                    .addComponent(regimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alergieoui)
                    .addComponent(allergienon)
                    .addComponent(jLabel3)
                    .addComponent(Maladienon)
                    .addComponent(Maladieoui)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maladiepanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allergiepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Nouveaux patients", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entete1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(entete1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MaladieouiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaladieouiMouseClicked
        maladiepanel1.setVisible(true);
    }//GEN-LAST:event_MaladieouiMouseClicked

    private void alergieouiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alergieouiMouseClicked
      allergiepanel.setVisible(true);
    }//GEN-LAST:event_alergieouiMouseClicked

    private void MaladienonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaladienonMouseClicked
       maladiepanel1.setVisible(false); 
    }//GEN-LAST:event_MaladienonMouseClicked

    private void allergienonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allergienonMouseClicked
allergiepanel.setVisible(false);
    }//GEN-LAST:event_allergienonMouseClicked
public void entete_tab(){
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Nom");
    model.addColumn("Taille (cm)");
    model.addColumn("Poids (kg)");
    model.addColumn("Age");
    model.addColumn("Sexe");
   // Ajoutez la colonne Quantité

    jTablenewpatients.setModel(model); // Définissez le modèle de tableau
    
    }
public   ArrayList<String> regimesNamesbreakfast = new ArrayList<>();
public void loadregimesNames() {
    connexion c = new connexion();
    String query = "SELECT name FROM dietplans"; // Modifié pour ne sélectionner que la colonne "name"
    try {
        PreparedStatement pstmt = c.con.prepareStatement(query);
        ResultSet rs = pstmt.executeQuery();

        while (rs.next()) {
            String name = rs.getString("name"); 
            regimesNamesbreakfast.add(name);
        }
      
        rs.close();
        pstmt.close();

    } catch (Exception e) {
        e.printStackTrace();
    } 
}
public void populateComboBox() {
    loadregimesNames();
        for (String regimeName : regimesNamesbreakfast) {
            regimes.addItem(regimeName);
        }}

public void remplir_tab(){
    DefaultTableModel model = (DefaultTableModel) jTablenewpatients.getModel();
 String sql = "SELECT Nom, height, weight, age, gender FROM new_patients WHERE rendezvous = CURDATE()";
   connexion c = new connexion();
  
    try { PreparedStatement pstmt = c.con.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();
            
            // Ajout des données au modèle de tableau
            while (rs.next()) {
                String nom = rs.getString("Nom");
                double taille = rs.getDouble("height");
                double poids = rs.getDouble("weight");
                int age = rs.getInt("age");
                String sexe = rs.getString("gender");
                model.addRow(new Object[]{nom, taille, poids, age, sexe});
            }
        } catch (SQLException e) {
            e.printStackTrace();
        
        }
    

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField But;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Description1;
    private javax.swing.JRadioButton Maladienon;
    private javax.swing.JRadioButton Maladieoui;
    private javax.swing.JTextField Nouvpoids;
    private javax.swing.JTextField Nouvtaille;
    private javax.swing.JRadioButton alergieoui;
    private javax.swing.JRadioButton allergienon;
    private javax.swing.JPanel allergiepanel;
    private javax.swing.ButtonGroup buttonGroupallergie;
    private javax.swing.ButtonGroup buttonGroupmaladie;
    private javax.swing.JTextArea desaller;
    private javax.swing.JTextArea desmalad;
    private component.Entete entete1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTablenewpatients;
    private javax.swing.JLabel label;
    private javax.swing.JPanel maladiepanel1;
    private javax.swing.JLabel poids;
    private javax.swing.JComboBox regimes;
    // End of variables declaration//GEN-END:variables
}
