/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package component;


import Model.Model_Day;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author Karim
 */
public class day extends javax.swing.JPanel {

    public Color getColor1() {
        return color1;
    }

    public void setColor1(Color color1) {
        this.color1 = color1;
    }

    public Color getColor2() {
        return color2;
    }

    public void setColor2(Color color2) {
        this.color2 = color2;
    }

    private Color color1;
    private Color color2;
    public day() {
        initComponents();
         setOpaque(false);
         petit_déjeuner.setText("petit_déjeuner");
         déjeuner.setText("déjeuner");
         dîner.setText("dîner");
        color1 = Color.BLACK;
        color2 = Color.WHITE;
    }
public void setData(Model_Day data) {
lbIcon.setIcon(data.getIcon());
 lbpetitdejeuner.setText(data.getPetit_déjeuner());
 lbdejeuner.setText(data.getDéjeuner());
 lbdiner.setText(data.getDîner());
 num.setText(data.getNum());
 


}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, color1, 0, getHeight(), color2);
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.setColor(new Color(255, 255, 255, 50));
        g2.fillOval(getWidth() - (getHeight() / 2), 10, getHeight(), getHeight());
        g2.fillOval(getWidth() - (getHeight() / 2) - 20, getHeight() / 2 + 20, getHeight(), getHeight());
        super.paintComponent(grphcs);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        num = new javax.swing.JLabel();
        petit_déjeuner = new javax.swing.JLabel();
        déjeuner = new javax.swing.JLabel();
        dîner = new javax.swing.JLabel();
        lbpetitdejeuner = new javax.swing.JLabel();
        lbdejeuner = new javax.swing.JLabel();
        lbdiner = new javax.swing.JLabel();
        lbIcon = new javax.swing.JLabel();

        num.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        num.setText("1");

        petit_déjeuner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        petit_déjeuner.setText("petit déjeuner");

        déjeuner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        déjeuner.setText("déjeuner");

        dîner.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dîner.setText("dîner");

        lbpetitdejeuner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbpetitdejeuner.setText("jLabel1");

        lbdejeuner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbdejeuner.setText("jLabel1");

        lbdiner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbdiner.setText("jLabel1");

        lbIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hamburger_30px.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(num)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(petit_déjeuner)
                    .addComponent(lbpetitdejeuner, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(déjeuner))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbdejeuner, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(dîner))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbdiner, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(lbIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(petit_déjeuner)
                            .addComponent(déjeuner)
                            .addComponent(dîner))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbpetitdejeuner)
                            .addComponent(lbdejeuner)
                            .addComponent(lbdiner)))
                    .addComponent(lbIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel déjeuner;
    private javax.swing.JLabel dîner;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbdejeuner;
    private javax.swing.JLabel lbdiner;
    private javax.swing.JLabel lbpetitdejeuner;
    private javax.swing.JLabel num;
    private javax.swing.JLabel petit_déjeuner;
    // End of variables declaration//GEN-END:variables
}
